export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  CLIENT_CREATE: "CLIENT_CREATE",
  CLIENT_UPDATE: "CLIENT_UPDATE",
  CLIENT_DELETE: "CLIENT_DELETE",

  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  GROUP_CREATE: "GROUP_CREATE",
  GROUP_UPDATE: "GROUP_UPDATE",
  GROUP_DELETE: "GROUP_DELETE",
  EVENT_CREATE: "EVENT_CREATE",
  EVENT_UPDATE: "EVENT_UPDATE",
  EVENT_DELETE: "EVENT_DELETE",
  TEMPLATE_CREATE: "TEMPLATE_CREATE",
  TEMPLATE_UPDATE: "TEMPLATE_UPDATE",
  TEMPLATE_DELETE: "TEMPLATE_DELETE",

  INVOICE_CREATE: "INVOICE_CREATE",
  INVOICE_UPDATE: "INVOICE_UPDATE",
  INVOICE_SEND: "INVOICE_SEND",
  INVOICE_RECORD_PAYMENT: "INVOICE_RECORD_PAYMENT",
  INVOICE_VOID: "INVOICE_VOID",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
